# In _config.yml
title: Powder Diffraction at ORNL
author: Yuanpeng Zhang
email: zhangy3@ornl.gov
logo: ornl_logo.png

html:
  # announcement: ""
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://powder.ornl.gov/

# Information about where the book exists on the web
repository:
  url : https://github.com/Kvieta1990/ornl-pd
  path_to_book: doc
  branch: main

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

# Bibliography settings
bibtex_bibfiles:
  - references.bib

execute:
  execute_notebooks: force

sphinx:
  config:
    bibtex_reference_style: author_year
